version: "3.9"
services:
  realsense_ros2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      #target: librealsense
    tty: true
    #stdin_open: true
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
